resolver: lts-7.19

packages:
- location:
    git: https://github.com/carliros/uuagc-builder.git
    commit: ff99e5f38c10c3664a528089244e9b57c281d10b
- '.'

extra-deps:
- uuagc-0.9.52.1
- uulib-0.9.22
- uuagc-cabal-1.0.6.0

flags: {}

extra-package-dbs: []

explicit-setup-deps:
  "*": true
